version: '3'
services:
  my-weather-app:
    build: ./my-weather-app
    ports:
      - "80:8080"  # Map port 8080 of the container to port 80 of the host
    environment:
      API_KEY: bb97533805fced5bb8e6af83e94dbee8
      S3_BUCKET_NAME: weatherforecast
      FLASK_ENV: production
      DB_USER: admin
      DB_PASSWORD: my-weather-app-db
      DB_HOST: my-weather-app-db.cnla9t80uygd.us-east-1.rds.amazonaws.com
      DB_NAME: weatherdb

  weather-data:
    build: ./weather-data
    ports:
      - "81:5001"  # Map port 5001 of the container to port 81 of the host
    environment:
      DB_USER: admin
      DB_PASSWORD: my-weather-app-db
      DB_HOST: my-weather-app-db.cnla9t80uygd.us-east-1.rds.amazonaws.com
      DB_NAME: weatherdb
